CREATE SCHEMA IF NOT EXISTS mmark;

CREATE TABLE "user"
(
    id            uuid         default gen_random_uuid() primary key,
    first_name    varchar(255)        not null,
    last_name     varchar(255)        not null,
    email         varchar(255) unique not null,
    password_hash varchar(255)        not null,
    registered_at timestamp           not null,
    visited_at    timestamp           not null,
    role          varchar(255) default 'USER',
    is_enabled    boolean      default true
);

CREATE TABLE session
(
    id            bigint generated by default as identity
        primary key,
    refresh_token uuid default gen_random_uuid(),
    expires_at    timestamp not null,
    user_id       uuid      not null
        constraint fk_session_user_id references "user"
);

CREATE TABLE mark
(
    id    bigint generated by default as identity
        primary key,
    title varchar(255) not null,
    text  text         not null,
    year  int          not null,
    month int          not null
        constraint month_constraint check ( month <= 12
) ,
    day       int          not null constraint day_constraint check ( month <= 31 ),
    created_at timestamp    not null,
    user_id   uuid         not null
        constraint fk_mark_user_id references "user"
);