debug: ${SPRING_DEBUG:false}
server:
  port: 9000

spring:
  application:
    name: make-mark

cache:
  user-maximum-size: 100000
  user-expired-time: 4h

postgres:
  url: ${POSTGRES_URL}
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  db: ${POSTGRES_DB}
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  max-active-connections: 25
  max-pending-queries: 100000
  max-connection-ttl: 120000
  max-idle-time: 300000

application:
  url: ${APP_URL}
  api-path: ${API_PATH:/}
  hash-salt: ${HASH_SALT}
  jwt-signing-key: ${JWT_SIGNING_KEY}
  access-token-ttl: ${ACCESS_TOKEN_TTL:1h}
  refresh-token-ttl: ${REFRESH_TOKEN_TTL:8h}
  session:
    max: ${SESSION_MAX:3}
    cron-delete: ${SESSION_CRON_DELETE:0 0 * * *}